language: node_js
node_js:
  - "9"

cache: yarn

install: yarn
script:
  - yarn build --base-href /jvmconfig-public/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/jvmconfig-public
  on:
    branch: master
