language: node_js
node_js:
  - "9"

cache: yarn

install: yarn
script:
  - yarn build
before_deploy: git config --global user.email publish@travis.github && git config --global user.name "Travis"
deploy:
  - edge: true
    skip_cleanup: true
    provider: development
    script: gulp publish
    on:
      branch: gh-pages
