language: node_js
node_js:
  - "9"

cache: yarn

install: yarn
script:
  - yarn build
  - echo 'jvmconfig.in' > public/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master
