language: node_js
node_js:
  - "9"

cache: yarn
install: yarn

jobs:
  include:
  # --------------------------------------------
  - stage: Build & Deploy
    skip_cleanup: true
    script:
      - yarn build
    deploy:
      provider: script
      script: yarn deploy
    on:
      tags: true
      all_branches: true
  # --------------------------------------------
